### ISSUE TITLE
Food detail screen (CTA to edit)

### ISSUE THREAD

**Issue by Ahmzyjazzy** [Flutter-Assembly/food_expiry_tracker#12]
https://www.figma.com/file/xjKua7FWHKMDXYMjk3iyK3/Flutter-Assembly---Food-Expiry-Tracker?node-id=24%3A3

![image](https://user-images.githubusercontent.com/24432247/98482956-9f499c80-21b9-11eb-8103-e3dc922360cd.png)

**Comment by Frankdroid7** [comment]
I will work on this issue.
