### ISSUE TITLE
About Screen

### ISSUE THREAD

**Issue by Ahmzyjazzy** [Flutter-Assembly/food_expiry_tracker#13]
https://www.figma.com/file/xjKua7FWHKMDXYMjk3iyK3/Flutter-Assembly---Food-Expiry-Tracker?node-id=24%3A4
see figma link

![image](https://user-images.githubusercontent.com/24432247/98482424-82d15280-2201-11eb-8f0b-08527f1a6f98.png)

**Comment by Frankdroid7** [comment]
I will work on this issue

**Comment by Ahmzyjazzy** [comment]
https://www.figma.com/file/xjKua7FWHKMDXYMjk3iyK3/Flutter-Assembly---Food-Expiry-Tracker?node-id=24%3A4
see figma link
